### ISSUE TITLE
Polish Translation

### ISSUE THREAD

**Issue by matthuisman** [matthuisman/plugin.video.dstv.now#1]
@xulek

https://github.com/matthuisman/plugin.video.dstv.now/blob/master/resources/language/resource.language.pl_pl/strings.po

Could you check that for me?
#30005 - I guessed from your Showmax translate
#30008 - Needs translation

**Comment by xulek** [comment]
I think its good in orginal

**Comment by matthuisman** [comment]
Thanks 👍
