### ISSUE TITLE
Channels buffer constantly

### ISSUE THREAD

**Issue by matthuisman** [matthuisman/plugin.video.dstv.now#2]
If Inpustream is set to VIDEO only, works 100%.

**Comment by matthuisman** [comment]
Seems fixed with
https://github.com/matthuisman/plugin.video.dstv.now/commit/3d40e64b56efe71b3d17ba003a2d113c786694f6

**Comment by reevawwit** [comment]
Does this app work for Xbox One S Kodi App? Would be great if i could watch DSTV from my Xbox
