### ISSUE TITLE
Xbox One S - Compatibility 

### ISSUE THREAD

**Issue by reevawwit** [matthuisman/plugin.video.dstv.now#4]
Does this app work for Xbox One S Kodi App? Would be great if i could watch DSTV from my Xbox

A few requests have been made for this - https://mybroadband.co.za/forum/threads/stream-dstv-now-on-xbox-one-using-a-browser.881632/ so hopefully it can work on the Xbox as well. 

Let me know :)

**Comment by matthuisman** [comment]
@reevawwit

Widevine in KODI does not work on UWP (Windows Store Apps & Xbox Apps).
I think it is due to them running in a sandbox and unable to execute third party binaries (Widevine DRM)
